console.log("\n Ejercicio 1 X-X-X-X-X-X-X-X-X-X-X-X\n");
import { ex1 } from "./ex1/ex1";
console.log("\n Ejercicio 2 X-X-X-X-X-X-X-X-X-X-X-X\n");
import { ex2 } from "./ex2/ex2";
console.log("\n Ejercicio 3 X-X-X-X-X-X-X-X-X-X-X-X\n");
import { ex3 } from "./ex3/ex3";
console.log("\n Ejercicio 4 X-X-X-X-X-X-X-X-X-X-X-X\n");
import { ex4 } from "./ex4/ex4";
console.log("\n Ejercicio 5 X-X-X-X-X-X-X-X-X-X-X-X\n");
import { ex5 } from "./ex5/ex5";
ex1();
ex2();
ex3();
ex4();
ex5();